// SPDX-FileCopyrightText: 2024 Ed
// SPDX-FileCopyrightText: 2024 metalgearsloth
// SPDX-FileCopyrightText: 2025 Ark
// SPDX-FileCopyrightText: 2025 ark1368
//
// SPDX-License-Identifier: MPL-2.0

using Content.Shared.Traits;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Lobby.UI.Roles;

[GenerateTypedNameReferences]
public sealed partial class TraitPreferenceSelector : Control
{
    public int Cost;
    public bool Visible
    {
        get => Container.Visible;
        set => Container.Visible = value;
    }

    public bool Preference
    {
        get => Checkbox.Pressed;
        set => Checkbox.Pressed = value;
    }

    public event Action<bool>? PreferenceChanged;

    public TraitPreferenceSelector(TraitPrototype trait)
    {
        RobustXamlLoader.Load(this);

        var text = trait.Cost != 0 ? $"[{trait.Cost}] " : "";
        text += Loc.GetString(trait.Name);

        Cost = trait.Cost;

        // Set the trait name
        NameLabel.Text = Loc.GetString(trait.Name);

        // Set the cost text and color
        string costText = "";
        if (trait.Cost > 0)
        {
            costText = $"-{trait.Cost}";
            CostLabel.FontColorOverride = Color.Red;
        }
        else if (trait.Cost < 0)
        {
            costText = $"+{-trait.Cost}";
            CostLabel.FontColorOverride = Color.Green;
        }
        else
        {
            costText = $"{trait.Cost}";
            CostLabel.FontColorOverride = Color.Gray;
        }

        CostLabel.Text = costText;

        // Set up button event
        TraitButton.OnPressed += OnTraitButtonPressed;

        if (trait.Description is { } desc)
        {
            Checkbox.ToolTip = Loc.GetString(desc);
        }

        UpdateButtonState();
    }

    public void SetTooltip(string tooltip)
    {
        TraitButton.TooltipSupplier = _ =>
        {
            var tip = new Robust.Client.UserInterface.CustomControls.Tooltip();
            tip.SetMessage(FormattedMessage.FromMarkupPermissive(tooltip));
            return tip;
        };
    }

    public void SetUnavailable(bool unavailable)
    {
        if (unavailable)
        {
            TraitButton.Disabled = true;
            TraitButton.ModulateSelfOverride = Color.Gray.WithAlpha(0.5f);
        }
        else
        {
            TraitButton.Disabled = false;
            TraitButton.ModulateSelfOverride = null;
        }
    }

    private void OnTraitButtonPressed(BaseButton.ButtonEventArgs args)
    {
        Checkbox.Pressed = !Checkbox.Pressed;
        PreferenceChanged?.Invoke(Preference);
        UpdateButtonState();
    }

    private void UpdateButtonState()
    {
        // Visual feedback for selection
        if (Checkbox.Pressed)
        {
            TraitButton.ModulateSelfOverride = Color.LightGreen.WithAlpha(0.3f);
        }
        else if (TraitButton.ModulateSelfOverride != Color.Gray.WithAlpha(0.5f))
        {
            TraitButton.ModulateSelfOverride = null;
        }
    }

    private void OnCheckBoxToggled(BaseButton.ButtonToggledEventArgs args)
    {
        PreferenceChanged?.Invoke(Preference);
    }
}
