// SPDX-License-Identifier: MPL-2.0

using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Shared.Utility;

namespace Content.Client.Lobby.UI.Roles;

/// <summary>
/// Minimal category container used by HumanoidProfileEditor to group trait controls
/// with expand/collapse behavior. Implemented here because the upstream type
/// is not present on this branch.
/// </summary>
public sealed class TraitCategoryButton : PanelContainer
{
    private static bool _allExpanded = true;

    private readonly Button _headerButton;

    // Avoid direct reference if VBoxContainer type is missing in this trimmed branch: implement minimal vertical stack.
    private readonly BoxContainer _rootContainer = new() { Orientation = BoxContainer.LayoutOrientation.Vertical };
    private readonly BoxContainer _traitsBox = new() { Orientation = BoxContainer.LayoutOrientation.Vertical };
    public BoxContainer TraitsContainer => _traitsBox;

    public TraitCategoryButton(string categoryName)
    {
        Name = $"TraitCategory:{categoryName}";

    AddChild(_rootContainer);

        _headerButton = new Button
        {
            Text = categoryName,
        };
        _headerButton.OnPressed += _ => SetExpanded(!_allExpanded);

    _rootContainer.AddChild(_headerButton);
    _rootContainer.AddChild(_traitsBox);

        SetExpanded(_allExpanded);
    }

    public static void SetAllExpanded(bool expanded)
    {
        _allExpanded = expanded;
    }

    public void SetExpanded(bool expanded)
    {
        _allExpanded = expanded;
    _traitsBox.Visible = expanded;
    }

    public void AddTrait(Control control)
    {
        _traitsBox.AddChild(control);
    }
}
